version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: tpachato   
    ports:
      - 3306:3306
    networks:
     - projectnetwork
     
  spring-boot:
    image: achrafzr/tpachat:1.0
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - projectnetwork 
    restart: on-failure     
  angular:
    image: achrafzr/app
    container_name: angular
    ports: 
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - projectnetwork
  
networks:
  projectnetwork:
